apiVersion: apps/v1
kind: Deployment
metadata:
  name: ensembl-ingest-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ensembl-ingest
  template:
    metadata:
      labels:
        app: ensembl-ingest
    spec:
      containers:
      - name: ensembl-ingest
        image: jclovek/ingest_api:latest
        ports:
        - containerPort: 5010
---
apiVersion: v1
kind: Service
metadata:
  name: ensembl-ingest
spec:
  selector:
    app: ensembl-ingest
  type: LoadBalancer
  ports:
  - port: 5010
    targetPort: 5010


