apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-api-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-api
  template:
    metadata:
      labels:
        app: mongo-api
    spec:
      containers:
      - name: mongo-api
        image: jclovek/mongo-api:latest
        ports:
        - containerPort: 5020
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-api
spec:
  selector:
    app: mongo-api
  type: LoadBalancer
  ports:
  - port: 5020
    targetPort: 5020


